### ISSUE TITLE
Commit lists per time only for 2 years

### ISSUE THREAD

**Issue by kronthto** [arzzen/git-quick-stats#130] opened 2021-05-17 17:19 UTC
Edit: This seems to be also the thing reported in a comment in https://github.com/arzzen/git-quick-stats/issues/123#issuecomment-826064228

**Describe the bug**
I want to run this tool in a big/old repo (2012-2021). When running "Git commits per hour" the numbers of commits appear too low. Upon investing, I found that is is due to a grep filtering on the year (probably to filter out lines that are not commits?): `grep -E "($startYear|$endYear)"` : 
https://github.com/arzzen/git-quick-stats/blob/f5c2b82f023e915da5eb9de6fe64088e9bfdaba0/git-quick-stats#L467

But this only matches/includes (in my example) **EXACTLY 2012 OR 2021**, and not any year in between.

**To Reproduce**
```
❯ git clone https://github.com/kronthto/git-stats-test.git
❯ cd git-stats-test

❯ git log
commit 555771df380c2d176750ff1737e97d84e518588d (HEAD -> master, origin/master)
Date:   Mon May 17 19:10:22 2021 +0200

    commit3

commit 520493f3794029548d477f6f4e3274f3b3829a3d
Date:   Tue Dec 22 13:37:00 2015 +0100

    commit2

commit 5895dd7011e214d66df2cb5928dc91c9f8f5ce46
Date:   Fri Dec 21 13:37:00 2012 +0100

    commit1


❯ _GIT_SINCE="2012-01-01" _GIT_UNTIL="2021-12-31" git-quick-stats -o
Git commits by hour:

	hour	sum
	00	0	|
	01	0	|
	02	0	|
	03	0	|
	04	0	|
	05	0	|
	06	0	|
	07	0	|
	08	0	|
	09	0	|
	10	0	|
	11	0	|
	12	0	|
	13	1	|████████████████████████████████████████
	14	0	|
	15	0	|
	16	0	|
	17	0	|
	18	0	|
	19	1	|████████████████████████████████████████
	20	0	|
	21	0	|
	22	0	|
	23	0	|
```

**Expected behavior**
There should be 2 commits (and thus a shorter bar at 19) for hour 13, but commit2 from 2015 is missing.

**Comment by kronthto** [comment] 2021-05-17 17:31
I locally makeshift patched this by simply changing the regex to `grep -E "[0-9]{4}"` and can make a PR for that if ok/wanted. But it feels hacky too and not stable for all scenarios again (4 numbers an appear in names/text too).

**Comment by tomice** [comment] 2021-06-07 04:53
I agree, this seems to be a duplicate of #123 where it describes issues with parsing the dates in the stats across multiple years. Closing this for now, but I'll link this for more information in the other ticket, as it will help with debugging. Thank you for the detailed description of the bug, steps to reproduce, and a possible solution!

**Closed by tomice** 2021-06-07 04:53 UTC
